# Generated by Django 2.1 on 2018-09-17 19:30

import cadastro.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_ini', models.DateField(default=datetime.date.today, verbose_name='Início')),
                ('dt_validade', models.DateField(default=cadastro.models.get_validade_default, verbose_name='Validade')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
        ),
        migrations.CreateModel(
            name='ComCota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(default='Insira seu comentário')),
                ('dt_com', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='comcotauser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-dt_com',),
            },
        ),
        migrations.CreateModel(
            name='ComPessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(default='Insira seu comentário')),
                ('dt_com', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='compessoauser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('dt_com',),
            },
        ),
        migrations.CreateModel(
            name='Cota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COTISTA', 'Cotista'), ('TRABALHADOR', 'Trabalhador'), ('BOLSISTA', 'Bolsista'), ('APOIADOR', 'Apoiador'), ('PERMUTA', 'Permuta')], default=cadastro.models.Tipo('Cotista'), max_length=15, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('AVISO', 'Aviso Prévio'), ('SUSPENSO', 'Suspenso')], default=cadastro.models.Status('Ativo'), max_length=15, verbose_name='Status')),
                ('higieniza', models.BooleanField(default=False, verbose_name='Higieniza')),
                ('dt_ini', models.DateField(default=datetime.date.today, verbose_name='Início')),
                ('dt_validade', models.DateField(default=cadastro.models.get_validade_default, verbose_name='Validade')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp_logradouro', models.CharField(default='Rua', max_length=25, verbose_name='Tipo')),
                ('logradouro', models.CharField(default='Rua', max_length=255, verbose_name='Logradouro')),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=255, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=255, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('cep', models.PositiveIntegerField(verbose_name='CEP')),
            ],
        ),
        migrations.CreateModel(
            name='Partilha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25, unique=True, verbose_name='Nome')),
                ('endereco', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partilha', to='cadastro.Endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prim_nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('dt_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('apelido', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Apelido')),
                ('rg', models.PositiveIntegerField(blank=True, null=True, verbose_name='RG')),
                ('cpf', models.BigIntegerField(blank=True, null=True, verbose_name='CPF')),
                ('profissao', models.CharField(blank=True, max_length=300, null=True, verbose_name='Profissão')),
                ('telefone', models.BigIntegerField(blank=True, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('endereco', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pessoa', to='cadastro.Endereco')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pessoa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=100, unique=True, verbose_name='Serviço')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
                ('frequencia', models.CharField(choices=[('SEMANAL', 'Semanal'), ('MENSAL', 'Mensal'), ('BIMESTRAL', 'Bimestral'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default=cadastro.models.Frenquencia('Mensal'), max_length=15, verbose_name='Frequência')),
                ('valor_adesao', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Valor Adesão')),
                ('max_adesao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail')),
                ('referencia', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Referência')),
                ('duracao_padrao', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Duração')),
            ],
        ),
        migrations.AddField(
            model_name='cota',
            name='outros',
            field=models.ManyToManyField(blank=True, related_name='cota_outros', to='cadastro.Pessoa'),
        ),
        migrations.AddField(
            model_name='cota',
            name='partilha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cota', to='cadastro.Partilha'),
        ),
        migrations.AddField(
            model_name='cota',
            name='principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cota', to='cadastro.Pessoa'),
        ),
        migrations.AddField(
            model_name='compessoa',
            name='fk_pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compessoa', to='cadastro.Pessoa'),
        ),
        migrations.AddField(
            model_name='comcota',
            name='fk_cota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comcota', to='cadastro.Cota'),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='cota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinatura', to='cadastro.Cota'),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinatura', to='cadastro.Servico'),
        ),
    ]
