# Generated by Django 2.1 on 2018-09-11 19:21

import cadastro.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('B', 'Bolsista'), ('T', 'Trabalhador'), ('C', 'Cotista'), ('P', 'Permuta'), ('A', 'Apoiador')], max_length=50)),
                ('status', models.CharField(choices=[('I', 'Inativo'), ('S', 'Suspenso'), ('A', 'Ativo'), ('P', 'Aviso Prévio')], max_length=50)),
                ('partilha', models.CharField(choices=[(2, 'São Paulo'), (1, 'Atibaia')], max_length=50)),
                ('higieniza', models.BooleanField(default=False)),
                ('dt_ini', models.DateField(default=datetime.date.today)),
                ('dt_validade', models.DateField(default=cadastro.models.get_validade_default)),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_nota', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('dt_nota',),
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prim_nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('dt_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('apelido', models.CharField(max_length=50, verbose_name='Apelido')),
                ('rg', models.PositiveIntegerField(verbose_name='RG')),
                ('cpf', models.BigIntegerField(verbose_name='CPF')),
                ('profissao', models.CharField(max_length=300, verbose_name='Profissão')),
                ('telefone', models.BigIntegerField(verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
        ),
        migrations.AddField(
            model_name='notas',
            name='fk_pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Pessoa'),
        ),
        migrations.AddField(
            model_name='cota',
            name='outros',
            field=models.ManyToManyField(to='cadastro.Pessoa'),
        ),
    ]
