# Generated by Django 2.1 on 2018-09-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cota',
            name='dt_validade',
        ),
        migrations.AlterField(
            model_name='cota',
            name='status',
            field=models.CharField(choices=[('P', 'Aviso Prévio'), ('S', 'Suspenso'), ('I', 'Inativo'), ('A', 'Ativo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cota',
            name='tipo',
            field=models.CharField(choices=[('P', 'Permuta'), ('A', 'Apoiador'), ('T', 'Trabalhador'), ('C', 'Cotista'), ('B', 'Bolsista')], max_length=50),
        ),
    ]
