# Generated by Django 2.1 on 2018-09-12 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20180911_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComPessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_com', models.DateTimeField(auto_now_add=True)),
                ('fk_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Pessoa')),
            ],
            options={
                'ordering': ('dt_com',),
            },
        ),
        migrations.RenameModel(
            old_name='Notas',
            new_name='ComCota',
        ),
        migrations.AlterModelOptions(
            name='comcota',
            options={'ordering': ('dt_com',)},
        ),
        migrations.RenameField(
            model_name='comcota',
            old_name='dt_nota',
            new_name='dt_com',
        ),
        migrations.RemoveField(
            model_name='comcota',
            name='fk_pessoa',
        ),
        migrations.AddField(
            model_name='comcota',
            name='fk_cota',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cadastro.Cota'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cota',
            name='partilha',
            field=models.CharField(choices=[('S', 'São Paulo'), ('A', 'Atibaia')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cota',
            name='status',
            field=models.CharField(choices=[('I', 'Inativo'), ('S', 'Suspenso'), ('A', 'Ativo'), ('P', 'Aviso Prévio')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cota',
            name='tipo',
            field=models.CharField(choices=[('B', 'Bolsista'), ('P', 'Permuta'), ('A', 'Apoiador'), ('C', 'Cotista'), ('T', 'Trabalhador')], max_length=50),
        ),
    ]
