# Generated by Django 2.1 on 2018-09-19 12:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0003_auto_20180919_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroDeCusto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=11, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('cnpj', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='CNPJ')),
                ('contato', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fornecedor', to='cadastro.Pessoa', verbose_name='contato')),
                ('trabalhador', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fornecedor', to='cadastro.Cota', verbose_name='trabalhador')),
            ],
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Data Ref')),
                ('descricao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição')),
                ('cdc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saidas.CentroDeCusto')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saidas.Fornecedor')),
            ],
        ),
    ]
